import { lerp } from '../utils/random.js';

export const STYLES = {
    gothic: {
        name: 'Gothic',
        // Silhouette
        silhouette: 'towered',
        towerProbability: 0.8,
        towerCount: { min: 1, max: 3 },
        towerHeightRatio: { min: 0.3, max: 0.6 },
        towerWidthRatio: { min: 0.15, max: 0.25 },
        wingProbability: 0.6,
        setbackLevels: 0,
        // Proportions
        aspectRatio: 0.6,
        baseHeightRatio: 0.08,
        crownHeightRatio: 0.15,
        // Angles
        chamferAmount: 0,
        spireAngle: 60,
        useSpires: true,
        // Windows
        windowStyle: 'arch',
        windowDensityX: 5,
        windowDensityY: 8,
        windowAspect: 0.4,
        // Ornaments
        ornamentLevel: 0.7,
        useRosette: true,
        usePinnacles: true,
        useButtresses: true,
        // Hatching
        hatchStyle: 'cross',
        hatchDensity: 0.3,
    },
    artdeco: {
        name: 'Art Deco',
        silhouette: 'setback',
        towerProbability: 0.9,
        towerCount: { min: 1, max: 1 },
        towerHeightRatio: { min: 0.2, max: 0.4 },
        towerWidthRatio: { min: 0.3, max: 0.4 },
        wingProbability: 0.3,
        setbackLevels: 3,
        aspectRatio: 0.5,
        baseHeightRatio: 0.12,
        crownHeightRatio: 0.08,
        chamferAmount: 0.15,
        spireAngle: 45,
        useSpires: true,
        windowStyle: 'grid',
        windowDensityX: 8,
        windowDensityY: 12,
        windowAspect: 0.7,
        ornamentLevel: 0.5,
        useRosette: false,
        usePinnacles: false,
        useButtresses: false,
        useSunburst: true,
        useVerticalLines: true,
        hatchStyle: 'vertical',
        hatchDensity: 0.4,
    },
    brutalist: {
        name: 'Brutalist',
        silhouette: 'block',
        towerProbability: 0.2,
        towerCount: { min: 0, max: 1 },
        towerHeightRatio: { min: 0.1, max: 0.2 },
        towerWidthRatio: { min: 0.4, max: 0.6 },
        wingProbability: 0.7,
        setbackLevels: 0,
        aspectRatio: 0.8,
        baseHeightRatio: 0.05,
        crownHeightRatio: 0.02,
        chamferAmount: 0,
        spireAngle: 0,
        useSpires: false,
        windowStyle: 'grid',
        windowDensityX: 10,
        windowDensityY: 8,
        windowAspect: 1.0,
        ornamentLevel: 0.1,
        useRosette: false,
        usePinnacles: false,
        useButtresses: false,
        hatchStyle: 'horizontal',
        hatchDensity: 0.5,
    },
    baroque: {
        name: 'Baroque',
        silhouette: 'domed',
        towerProbability: 0.5,
        towerCount: { min: 0, max: 2 },
        towerHeightRatio: { min: 0.15, max: 0.3 },
        towerWidthRatio: { min: 0.12, max: 0.18 },
        wingProbability: 0.8,
        setbackLevels: 0,
        aspectRatio: 0.7,
        baseHeightRatio: 0.1,
        crownHeightRatio: 0.25,
        chamferAmount: 0,
        spireAngle: 0,
        useSpires: false,
        useDome: true,
        windowStyle: 'arch',
        windowDensityX: 5,
        windowDensityY: 6,
        windowAspect: 0.5,
        ornamentLevel: 0.9,
        useRosette: false,
        usePinnacles: false,
        useButtresses: false,
        useColumns: true,
        usePediments: true,
        hatchStyle: 'diagonal',
        hatchDensity: 0.25,
    },
    scifi: {
        name: 'Sci-Fi',
        silhouette: 'angular',
        towerProbability: 0.7,
        towerCount: { min: 1, max: 2 },
        towerHeightRatio: { min: 0.3, max: 0.5 },
        towerWidthRatio: { min: 0.1, max: 0.2 },
        wingProbability: 0.4,
        setbackLevels: 2,
        aspectRatio: 0.45,
        baseHeightRatio: 0.15,
        crownHeightRatio: 0.1,
        chamferAmount: 0.25,
        spireAngle: 30,
        useSpires: true,
        windowStyle: 'slit',
        windowDensityX: 12,
        windowDensityY: 20,
        windowAspect: 0.2,
        ornamentLevel: 0.3,
        useRosette: false,
        usePinnacles: false,
        useButtresses: false,
        useAntennae: true,
        hatchStyle: 'diagonal',
        hatchDensity: 0.6,
    },
    ruin: {
        name: 'Ruin',
        silhouette: 'broken',
        towerProbability: 0.4,
        towerCount: { min: 0, max: 2 },
        towerHeightRatio: { min: 0.1, max: 0.3 },
        towerWidthRatio: { min: 0.15, max: 0.25 },
        wingProbability: 0.5,
        setbackLevels: 0,
        aspectRatio: 0.65,
        baseHeightRatio: 0.1,
        crownHeightRatio: 0.05,
        chamferAmount: 0,
        spireAngle: 50,
        useSpires: false,
        windowStyle: 'broken',
        windowDensityX: 4,
        windowDensityY: 5,
        windowAspect: 0.5,
        ornamentLevel: 0.2,
        decay: 0.4,
        useVegetation: true,
        hatchStyle: 'random',
        hatchDensity: 0.2,
    },
};

// Apply character modifier to style
export function applyCharacter(baseStyle, character) {
    return {
        ...baseStyle,
        towerProbability: lerp(baseStyle.towerProbability * 0.5, Math.min(1, baseStyle.towerProbability * 1.5), character),
        towerHeightRatio: {
            min: lerp(baseStyle.towerHeightRatio.min * 0.5, baseStyle.towerHeightRatio.min * 1.2, character),
            max: lerp(baseStyle.towerHeightRatio.max * 0.5, baseStyle.towerHeightRatio.max * 1.2, character),
        },
        ornamentLevel: lerp(baseStyle.ornamentLevel * 0.3, Math.min(1, baseStyle.ornamentLevel * 1.5), character),
        windowDensityX: Math.round(lerp(baseStyle.windowDensityX * 0.6, baseStyle.windowDensityX * 1.2, character)),
        windowDensityY: Math.round(lerp(baseStyle.windowDensityY * 0.6, baseStyle.windowDensityY * 1.2, character)),
        setbackLevels: Math.round(lerp(0, baseStyle.setbackLevels * 1.5, character)),
        hatchDensity: lerp(baseStyle.hatchDensity * 0.5, baseStyle.hatchDensity * 1.2, character),
    };
}

export function getStyle(styleName, character = 0.5) {
    const base = STYLES[styleName] || STYLES.gothic;
    return applyCharacter(base, character);
}
